# Generated by Django 4.0.3 on 2022-04-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
