# Generated by Django 4.0.3 on 2022-04-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_options_alter_comments_post_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
