# Generated by Django 4.0.3 on 2022-04-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comments_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upvote',
            field=models.IntegerField(null=True),
        ),
    ]
